In [1]:
import pe_ode as pe
import numpy as np
from numpy import linalg as LA
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp, odeint

In [2]:
yhat_model1=np.array([[0,1.4,6.3,10.5,14.2,17.6,21.4,23.0,27.0,30.5,34.4,38.8,41.6,43.5,45.3]])
t_model1 = np.array([0,1,2,3,4,5,6,7,9,11,14,19,24,29,39])
k_model1 = np.array([0.4577e-5,0.2796e-3])

In [3]:
def model1_scaled_pe(u,kbar):
    dudt = kbar[0]*(126.2/91.9-u)*(1-u)**2-kbar[1]*u**2
    return dudt

In [4]:
k_guess1 = np.array([1e-6,1e-6])
yc1 = 91.9
tc1 = t_model1[-1]
yhat_bar1 = yhat_model1/yc1
tbar1 = t_model1/tc1
kbar1 = np.empty(2)
kbar1[0] = k_model1[0]*yc1**2*tc1
kbar1[1] = k_model1[1]*yc1*tc1
kbar10 = np.empty(2)
kbar10[0] = k_guess1[0]*yc1**2*tc1
kbar10[1] = k_guess1[1]*yc1*tc1
Q1 = np.eye(1)

In [5]:
opts = [1e-3,1e-8,1e-8,100]
pe1 = pe.lm(model1_scaled_pe,yhat_bar1,Q1,kbar10,tbar1,opts)

Iteration | Objective function | Reduced gradient |   mu   |   rho
g is
[-0.75455613  0.01324812]
L0 - L is  0.21807260268006362
S0 is 
0.05616891803913487
g is
[-0.12995515  0.00794591]
         1|          5.6169e-02|          1.18e-01| 4.7e-05| 1.9e+00
Iter end



L0 - L is  0.02200119149448777
S0 is 
0.011577476850480238
g is
[-0.01471194 -0.0062424 ]
         2|          1.1577e-02|          1.83e-02| 1.6e-05| 2.0e+00
Iter end



L0 - L is  0.0005532845467661847
S0 is 
0.010241550562251202
g is
[-0.0008441  -0.00889802]
         3|          1.0242e-02|          1.11e-03| 5.2e-06| 2.4e+00
Iter end



L0 - L is  0.00239832326923163
S0 is 
0.003945334274879391
g is
[-0.00095738 -0.00306044]
         4|          3.9453e-03|          1.70e-03| 1.7e-06| 2.6e+00
Iter end



L0 - L is  0.0007093564162018487
S0 is 
0.002589752481151463
g is
[ 1.65670196e-04 -8.30387273e-05]
         5|          2.5898e-03|          2.50e-04| 5.8e-07| 1.9e+00
Iter end



L0 - L is  3.5640532271315497e-07
S0

In [6]:
pe11 = pe.lm(model1_scaled_pe,yhat_bar1,Q1,kbar1,tbar1,opts)

Iteration | Objective function | Reduced gradient |   mu   |   rho
g is
[-2.68253920e-06 -2.09193598e-07]
L0 - L is  6.584423058814862e-11
S0 is 
0.002589007417512477
g is
[3.72099524e-07 2.99838870e-07]
         1|          2.5890e-03|          5.61e-07| 1.1e-04| 5.0e+03
Iter end



L0 - L is  1.228716328073398e-11
         2|          2.5892e-03|          5.61e-07| 2.1e-04|-1.6e+04
Iter end



L0 - L is  1.2281246685591193e-11
         3|          2.5890e-03|          5.61e-07| 8.6e-04|-1.4e+03
Iter end



L0 - L is  1.2116335059295066e-11
         4|          2.5894e-03|          5.61e-07| 6.9e-03|-2.9e+04
Iter end



L0 - L is  8.792711300820538e-12
         5|          2.5891e-03|          5.61e-07| 1.1e-01|-5.8e+03
Iter end



L0 - L is  1.6822924882724592e-12
         6|          2.5891e-03|          5.61e-07| 3.5e+00|-4.7e+04
Iter end



L0 - L is  1.5397810776888095e-13
         7|          2.5890e-03|          5.61e-07| 2.2e+02|-1.4e+05
Iter end



         8|          2.5890

In [7]:
print(pe1)

[array([1.50759275, 1.00216656]), array([[0.        , 0.04950332, 0.09275547, 0.13086466, 0.16468032,
        0.19486122, 0.22194261, 0.24634344, 0.28844632, 0.32330447,
        0.36527369, 0.41564105, 0.44971618, 0.47321888, 0.50118087]]), [21, 'h']]


In [8]:
print(pe11)

[array([1.50760527, 1.00222759]), array([[0.        , 0.04950393, 0.09275664, 0.13086442, 0.16468089,
        0.19486286, 0.22194423, 0.24634374, 0.28844139, 0.32331404,
        0.36527209, 0.41564501, 0.44972148, 0.47320257, 0.50117965]]), [8, 'h']]


In [9]:
print(pe1[0])
print(pe11[0])

[1.50759275 1.00216656]
[1.50760527 1.00222759]


In [10]:
pe1[0]/pe11[0]

array([0.9999917 , 0.99993911])

In [11]:
t_model2 = np.array([0,5.63,11.32,16.97,22.62,34.00,39.70,45.20,169.7],dtype='f')*1e-4
yhat_model2 = np.array([[1,0.828,0.704,0.622,0.565,0.499,0.482,0.470,0.443],
                   [0,0.0737,0.1130,0.1322,0.1400,0.1468,0.1477,0.1477,0.1476]],dtype='f')
k_model2 = np.array([354.61,400.23])

In [12]:
def model2_scaled_pe(u,kbar):
    K1 = 0.242
    K2 = 0.428
    M = 1
    r1 = kbar[0]*(u[0]**2-u[1]*(2/M-2*u[0]-u[1])/(3*K1))
    r2 = kbar[1]*(u[0]*u[1]-(1/M-u[0]-2*u[1])*(2/M-2*u[0]-u[1])/(9*K2))
    dudt = np.empty(2)
    dudt[0] = -r1-r2
    dudt[1] = r1/2-r2
    return dudt

In [13]:
k20 = np.array([1e4,1e4])
M = 1.0
yhat_bar2 = yhat_model2/M
tc2 = t_model2[-1]
tbar2 = t_model2/tc2
kbar2 = np.empty(2)
kbar2[0] = k_model2[0]*M*tc2
kbar2[1] = k_model2[1]*M*tc2
kbar20 = np.empty(2)
kbar20[0] = k20[0]*(M*tc2)
kbar20[1] = k20[1]*(M*tc2)
Q2 = np.eye(2)

In [14]:
kbar20t = np.array([5e2,5e2])*tc2
opts2 = [1e-3,1e-8,1e-8,100]
pe2 = pe.lm(model2_scaled_pe,yhat_bar2,Q2,kbar20t,tbar2,opts2)

Iteration | Objective function | Reduced gradient |   mu   |   rho
g is
[0.00542316 0.00042156]
L0 - L is  0.009569625049052307
S0 is 
0.0018881295090129372
g is
[-0.0032866  -0.00017147]
         1|          1.8881e-03|          1.78e-02| 4.1e-05| 1.7e+00
Iter end



L0 - L is  0.0009449901650130005
S0 is 
1.501009458312292e-05
g is
[-1.88659425e-04 -9.36132322e-06]
         2|          1.5010e-05|          1.13e-03| 1.4e-05| 2.0e+00
Iter end



L0 - L is  3.979931487724671e-06
S0 is 
7.0517525305847385e-06
g is
[-1.45629074e-06 -2.59302248e-08]
         3|          7.0518e-06|          8.76e-06| 4.6e-06| 2.0e+00
Iter end



L0 - L is  2.4276302284464213e-10
         4|          7.0539e-06|          8.76e-06| 9.2e-06|-8.7e+00
Iter end



L0 - L is  2.4309811626765077e-10
         5|          7.0539e-06|          8.76e-06| 3.7e-05|-9.0e+00
Iter end



L0 - L is  2.4510266569563945e-10
S0 is 
7.050877500183028e-06
g is
[-7.28514748e-09 -2.13931264e-10]
         6|          7.0509e-06|  

In [15]:
rho = 0.9
1-(2*rho-1)**3

0.4879999999999999

In [16]:
print(pe2)

[array([6.01761552, 6.79179215]), array([[1.        , 0.82833426, 0.70541073, 0.62146827, 0.56432719,
        0.49898481, 0.48109912, 0.4693483 , 0.44329901],
       [0.        , 0.07379112, 0.11221202, 0.13131402, 0.14069775,
        0.14727296, 0.14814621, 0.14843817, 0.14773838]]), [18, 'h']]


In [17]:
pe2 = pe.lm(model2_scaled_pe,yhat_bar2,Q2,kbar2,tbar2,[1e-3,1e-8,1e-8,100])

Iteration | Objective function | Reduced gradient |   mu   |   rho
g is
[5.32582329e-07 3.66306911e-08]
L0 - L is  3.4983325800685525e-11
         1|          7.0540e-06|          3.20e-06| 3.2e-04|-8.5e+01
Iter end



L0 - L is  3.689340847063574e-11
         2|          7.0513e-06|          3.20e-06| 1.3e-03|-7.7e+00
Iter end



L0 - L is  4.7022189531153945e-11
         3|          7.0511e-06|          3.20e-06| 1.0e-02|-1.6e+00
Iter end



L0 - L is  1.0609504053118205e-10
         4|          7.0514e-06|          3.20e-06| 1.6e-01|-3.9e+00
Iter end



L0 - L is  3.091139208953995e-10
         5|          7.0511e-06|          3.20e-06| 5.2e+00|-4.0e-01
Iter end



L0 - L is  3.457448650762977e-11
         6|          7.0515e-06|          3.20e-06| 3.4e+02|-1.5e+01
Iter end



         7|          7.0515e-06|          3.20e-06| 3.4e+02|-1.5e+01
Iter end





In [18]:
print(pe2)

[array([6.01773145, 6.79190282]), array([[1.        , 0.82833158, 0.705407  , 0.62146446, 0.56432375,
        0.49898246, 0.48109726, 0.46934663, 0.44329901],
       [0.        , 0.0737921 , 0.11221306, 0.13131483, 0.14069831,
        0.14727319, 0.14814634, 0.14843829, 0.14773838]]), [7, 'h']]


In [19]:
Y,J = pe.state_jacob_int(model2_scaled_pe,yhat_bar2[:,0],kbar20,tbar2)

In [20]:
print(Y)

[[1.         0.44331414 0.44329307 0.4432931  0.44329309 0.44329309
  0.44329309 0.44329309 0.44329309]
 [0.         0.14775787 0.14773596 0.14773599 0.14773598 0.14773598
  0.14773598 0.14773598 0.14773598]]


In [21]:
print(*J,sep='\n')

[[0. 0.]
 [0. 0.]]
[[-4.38236014e-07 -7.88192754e-07]
 [ 2.19120901e-07 -1.29974882e-06]]
[[ 4.89706450e-10  6.40922748e-10]
 [-2.32276129e-10  1.09202552e-09]]
[[-6.80755065e-11 -9.65273604e-11]
 [ 2.88830072e-11 -3.18692351e-10]]
[[ 5.46895495e-11  6.23940348e-11]
 [-2.33607529e-11  2.18315751e-10]]
[[-2.61679587e-11  2.82837751e-11]
 [ 5.98140432e-12 -1.30885301e-10]]
[[-3.88541674e-13  7.26346019e-11]
 [-6.73578764e-12 -4.37529818e-11]]
[[-2.49307383e-13  4.59197942e-11]
 [-4.27221023e-12 -2.77239407e-11]]
[[ 2.80946635e-12  3.77180756e-11]
 [-4.26672754e-12 -4.85938845e-12]]


In [22]:
S,r=pe.objective_func(yhat_bar2,Y,Q2,9)
print(*r,sep='\n')

[ 0.00000000e+00  3.84685867e-01  2.60706927e-01  1.78706882e-01
  1.21706909e-01  5.57069187e-02  3.87069005e-02  2.67069062e-02
 -2.93103466e-04]
[ 0.00000000e+00 -7.40578714e-02 -3.47359652e-02 -1.55359849e-02
 -7.73597909e-03 -9.35988339e-04 -3.59866586e-05 -3.59864678e-05
 -1.35987824e-04]


In [23]:
H,g=pe.Hg(J,Q2,r,2,9)
print(H)
print(g)

[[2.40065077e-13 6.06123736e-14]
 [6.06123736e-14 2.31059660e-12]]
[1.84682353e-07 2.06821488e-07]


In [24]:
K = np.diag(kbar20)
Hr = K@H@K
gr = K@g

In [38]:
w, v = LA.eig(Hr)
print(w)
v.T@v

[6.86236077e-09 6.65918176e-08]


array([[1., 0.],
       [0., 1.]])

In [25]:
print(K)
print(Hr)
print(gr)

[[169.69999298   0.        ]
 [  0.         169.69999298]]
[[6.91341512e-09 1.74552045e-09]
 [1.74552045e-09 6.65407633e-08]]
[3.1340594e-05 3.5097605e-05]


In [26]:
mu = max(np.diag(Hr))
print(mu)

6.654076329740317e-08


In [27]:
hr = pe.svdsolve(Hr+1e1*mu*np.eye(2),-gr)

In [28]:
print(hr)

[-46.49131282 -47.84005768]


In [29]:
kbar20+hr

array([123.20868017, 121.85993531])

In [30]:
Y,J = pe.state_jacob_int(model2_scaled_pe,yhat_bar2[:,0],kbar20+hr,tbar2)

In [31]:
print(K@hr)

[-7889.57545923 -8118.45745223]


In [32]:
h = pe.svdsolve(H,-g)

In [33]:
print(h)

[-751679.98905972  -69791.6631466 ]
