In [1]:
import GN_ode as gn
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp, odeint

In [3]:
A = np.array([[1,2],[3,4]],dtype='f')
b_col = np.array([[2],[3]],dtype='f')
b_1d = np.array([2,3],dtype='f')
mm_col = np.matmul(A,b_col)
mm_1d = np.matmul(A,b_1d)
at_col = A@b_col
at_1d = A@b_1d
print('mm_col:\n',mm_col)
print('mm_1d:\n',mm_1d)
print('at_col:\n',at_col)
print('at_1d:\n',at_1d)
dot_col = np.dot(A,b_col)
dot_1d = np.dot(A,b_1d)
ast_col = A*b_col
ast_1d = A*b_1d
print('dot_col:\n',dot_col)
print('dot_1d:\n',dot_1d)
print('ast_col:\n',ast_col)
print('ast_1d:\n',ast_1d)

mm_col:
 [[ 8.]
 [18.]]
mm_1d:
 [ 8. 18.]
at_col:
 [[ 8.]
 [18.]]
at_1d:
 [ 8. 18.]
dot_col:
 [[ 8.]
 [18.]]
dot_1d:
 [ 8. 18.]
ast_col:
 [[ 2.  4.]
 [ 9. 12.]]
ast_1d:
 [[ 2.  6.]
 [ 6. 12.]]


* np.matmul and @ produced same result
* np.dot and * are different
* Don't use * !!!!!!

Python matrix muliplication rules.
$$\mathbf{A}=\begin{bmatrix}1&2\\3&4\end{bmatrix},~~\mathbf{b}=\begin{bmatrix}2\\3\end{bmatrix}$$
$$\mathbf{Ab}=\begin{bmatrix}8\\18\end{bmatrix}$$

In [9]:
a = np.array([[[1,2],[4,5]],[[3,2],[7,8]]])
b = np.array([[2,3],[3,4]])
def aaa(a,b):
    return a,b

d = a,b

In [18]:
import multiprocessing as mp
print("Number of processors: ",mp.cpu_count())

Number of processors:  8
